
[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.6"

[[constraint]]
  branch = "master"
  name = "github.com/GeertJohan/go.rice"

[[constraint]]
  branch = "master"
  name = "github.com/blockassets/cgminer_client"

[[constraint]]
  branch = "master"
  name = "github.com/jpillora/overseer"
