
[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.6"

[[constraint]]
  branch = "master"
  name = "github.com/GeertJohan/go.rice"

[[constraint]]
  branch = "master"
  name = "github.com/blockassets/cgminer_client"

[[constraint]]
  branch = "master"
  name = "github.com/jpillora/overseer"

[[constraint]]
  name = "go.uber.org/fx"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/Jeffail/gabs"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.2"

[[constraint]]
  name = "github.com/mholt/archiver"
  branch = "master"

[[constraint]]
  name = "github.com/blockassets/node_exporter"
  branch = "blockassets"
